### ISSUE TITLE
What Are the Sources of the Scraped Data?

### ISSUE THREAD

**Issue by guozixunnicolas** [Metacreation-Lab/MetaMIDI-Dataset#1]
Hi there,

Thank you for putting together this dataset! 

The paper mentions that information about the websites scraped will be provided, but I couldn’t find it. Could you please share this info (similar to the GigaMidi dataset)?

Many thanks! 
Best,
Nicolas

**Comment by punchline10** [comment]
Hi Nicolas,

The following Zenodo link includes information about the scraped websites, but you will need to formally request it. 
https://zenodo.org/records/5142664#.YQN3c5NKgWo 

I don't manage that particular Zenodo account, but as far as I know, you will have access there once granted access to the Zenodo link.

Regards,
Keon

**Comment by guozixunnicolas** [comment]
Thank you Keon!!
